In [1]:
import pandas as pd

In [2]:
df_contractors = pd.read_excel('./Contractor Onboarding Data_01.01.16 - 09.04.19.xlsx',header=14,na_values='-')

In [3]:
df_contractors['year'] = pd.to_datetime(df_contractors['Account Creation Date']).dt.year

In [4]:
df_contractors.groupby('year').year.count()

year
2016    1473
2017    1233
2018    1345
2019     995
Name: year, dtype: int64

In [5]:
df_1 = df_contractors.loc[df_contractors['year'] == 2016]

In [6]:
import random
import numpy as np

def my_train_test_split(df,train_size=0.8):
    index_list = list(df.index)
    random.shuffle(index_list)
    train_index = index_list[0:int(len(index_list)*train_size)]
    df['train_test'] = np.array([0]*len(index_list))
    df.loc[train_index,'train_test'] = 1
    return df

In [7]:
df_contain = pd.DataFrame()
for i in [2016,2017,2018,2019]:
    df = df_contractors.loc[(df_contractors['year'] == i),['Dealer ID','year']]
    df = my_train_test_split(df)
    df_contain = pd.concat([df_contain,df],axis=0)

In [8]:
df = df_contractors.loc[(df_contractors['year'] == 2016),['Dealer ID','year']]

In [9]:
df_contain

     Dealer ID  year  train_test
0       C15306  2016           1
1       C15309  2016           1
2       C15310  2016           0
3       C15311  2016           1
4       C15312  2016           1
5       C15313  2016           1
6       C15314  2016           1
7       C15315  2016           1
8       C15316  2016           1
9       C15317  2016           1
10      C15318  2016           1
11      C15319  2016           1
12      C15320  2016           1
13      C15321  2016           1
14      C15322  2016           1
15      C15323  2016           1
16      C15324  2016           1
17      C15325  2016           1
18      C15326  2016           1
19      C15327  2016           0
20      C15328  2016           1
21      C15329  2016           1
22      C15330  2016           1
23      C15331  2016           0
24      C15332  2016           1
25      A09439  2016           1
26      C15333  2016           1
27      C15334  2016           1
28      C15335  2016           1
29      C15336  2016           1
...        ...   ...         ...
5016    C20611  2019           1
5017    C20612  2019           1
5018    C20613  2019           1
5019    C20614  2019           1
5020    C20615  2019           1
5021    C20616  2019           1
5022    C20617  2019           1
5023    C20618  2019           0
5024    C20619  2019           1
5025    C20620  2019           1
5026    C20621  2019           0
5027    C20622  2019           0
5028    C20623  2019           1
5029    C20624  2019           1
5030    C20625  2019           1
5031    C20626  2019           1
5032    C20627  2019           1
5033    C20628  2019           0
5034    C20629  2019           1
5035    C20630  2019           1
5036    C20631  2019           1
5037    C20632  2019           1
5038    C20633  2019           1
5039    C20634  2019           1
5040    C20635  2019           1
5041    C20636  2019           1
5042    C20637  2019           1
5043    C20638  2019           1
5044    C20639  2019           1
5045    C20640  2019           1

[5046 rows x 3 columns]

In [10]:
df_contain.to_csv('./train_test_split.csv')